from enum import Enum

class RuntimeState(str, Enum):
    CREATED = "CREATED"
    WAITING_FOR_PRESENTATION = "WAITING_FOR_PRESENTATION"
    INTRODUCTION = "INTRODUCTION"
    PRESENTING = "PRESENTING"
    QUESTION_ANSWER = "QUESTION_ANSWER"
    COMPLETED = "COMPLETED"
