from enum import Enum

class SessionEvent(str, Enum):
    SESSION_STARTED = "SESSION_STARTED"
    PRESENTATION_STARTED = "PRESENTATION_STARTED"
    SLIDE_CHANGED = "SLIDE_CHANGED"
    CHAT_MESSAGE = "CHAT_MESSAGE"
    QUESTION_RECEIVED = "QUESTION_RECEIVED"
    QUESTION_ANSWERED = "QUESTION_ANSWERED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
