from enum import Enum

class PresentationMode(str, Enum):
    NONE = "NONE"
    SCREEN_SHARING = "SCREEN_SHARING"
    POWERPOINT_SHARED = "POWERPOINT_SHARED"
    VIDEO_PLAYBACK = "VIDEO_PLAYBACK"
    BLANK_SCREEN = "BLANK_SCREEN"
    WAITING_SCREEN = "WAITING_SCREEN"
    LOADING = "LOADING"
    ENDED = "ENDED"
