from app.core.exceptions import LLMResponseValidationError

def validate_introduction_response(data: dict):
    """
    Validates welcome introduction elements generated by the LLM.
    """
    required_strings = [
        "greeting", "wait_message", "audio_check",
        "ice_breaker", "meeting_join_message",
        "late_joiner_message", "start_confirmation"
    ]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in introduction response."
            )

    agenda = data.get("agenda")
    if agenda is None or not isinstance(agenda, list):
        raise LLMResponseValidationError(
            "Required field 'agenda' is missing or is not a list in introduction response."
        )
    for idx, item in enumerate(agenda):
        if not isinstance(item, str) or not item.strip():
            raise LLMResponseValidationError(
                f"Element at agenda[{idx}] must be a non-empty string."
            )

def validate_slide_response(data: dict):
    """
    Validates slide scripts, transitions, and predicted Q&A arrays.
    """
    required_strings = ["narration", "interactive_prompt", "learning_objective"]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in slide response."
            )

    takeaways = data.get("key_takeaways")
    if takeaways is None or not isinstance(takeaways, list):
        raise LLMResponseValidationError(
            "Required field 'key_takeaways' is missing or is not a list in slide response."
        )
    for idx, item in enumerate(takeaways):
        if not isinstance(item, str) or not item.strip():
            raise LLMResponseValidationError(
                f"Element at key_takeaways[{idx}] must be a non-empty string."
            )

    questions = data.get("expected_questions")
    if questions is None or not isinstance(questions, list):
        raise LLMResponseValidationError(
            "Required field 'expected_questions' is missing or is not a list in slide response."
        )
    for idx, q in enumerate(questions):
        if not isinstance(q, dict):
            raise LLMResponseValidationError(
                f"Element at expected_questions[{idx}] must be a JSON object."
            )
        for field in ["question", "answer"]:
            q_val = q.get(field)
            if not q_val or not isinstance(q_val, str) or not q_val.strip():
                raise LLMResponseValidationError(
                    f"Required field '{field}' inside expected_questions[{idx}] is missing or empty."
                )
        if "confidence" in q and q["confidence"] is not None:
            if not isinstance(q["confidence"], (int, float)):
                raise LLMResponseValidationError(
                    f"Field 'confidence' inside expected_questions[{idx}] must be a float."
                )
        if "reference_slide" in q and q["reference_slide"] is not None:
            if not isinstance(q["reference_slide"], int):
                raise LLMResponseValidationError(
                    f"Field 'reference_slide' inside expected_questions[{idx}] must be an integer."
                )
        if "follow_up_questions" in q and q["follow_up_questions"] is not None:
            if not isinstance(q["follow_up_questions"], list):
                raise LLMResponseValidationError(
                    f"Field 'follow_up_questions' inside expected_questions[{idx}] must be a list."
                )

    # Validate video_script sub-schema if present
    vs = data.get("video_script")
    if vs is not None:
        if not isinstance(vs, dict):
            raise LLMResponseValidationError("Field 'video_script' must be a JSON object.")
        for field in ["before_video", "after_video", "resume_message"]:
            vs_val = vs.get(field)
            if not vs_val or not isinstance(vs_val, str) or not vs_val.strip():
                raise LLMResponseValidationError(
                    f"Required field '{field}' inside video_script is missing or empty."
                )

def validate_closing_response(data: dict):
    """
    Validates final closing scripts.
    """
    required_strings = ["summary", "congratulations", "next_steps"]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in closing response."
            )
