from app.core.exceptions import LLMResponseValidationError

def validate_introduction_response(data: dict):
    """
    Validates welcome introduction elements generated by the LLM.
    """
    required_strings = [
        "greeting", "wait_message", "audio_check",
        "ice_breaker", "meeting_join_message",
        "late_joiner_message", "start_confirmation"
    ]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in introduction response."
            )

    agenda = data.get("agenda")
    if agenda is None or not isinstance(agenda, list):
        raise LLMResponseValidationError(
            "Required field 'agenda' is missing or is not a list in introduction response."
        )
    for idx, item in enumerate(agenda):
        if not isinstance(item, str) or not item.strip():
            raise LLMResponseValidationError(
                f"Element at agenda[{idx}] must be a non-empty string."
            )

def validate_slide_response(data: dict, has_video: bool):
    """
    Validates slide scripts, transitions, and properties.
    Ensures video_script is conditionally required only if the slide has videos (v1.6).
    """
    # 1. Enforce required fields: narration and learning_objective
    required_strings = ["narration", "learning_objective"]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in slide response."
            )

    takeaways = data.get("key_takeaways")
    if takeaways is None or not isinstance(takeaways, list):
        raise LLMResponseValidationError(
            "Required field 'key_takeaways' is missing or is not a list in slide response."
        )
    for idx, item in enumerate(takeaways):
        if not isinstance(item, str) or not item.strip():
            raise LLMResponseValidationError(
                f"Element at key_takeaways[{idx}] must be a non-empty string."
            )

    # 2. Enforce conditional rules for video_script
    vs = data.get("video_script")
    if has_video:
        if vs is None or not isinstance(vs, dict):
            raise LLMResponseValidationError(
                "Required field 'video_script' is missing or not a JSON object for a slide with videos."
            )
        for field in ["before_video", "after_video", "resume_message"]:
            vs_val = vs.get(field)
            if not vs_val or not isinstance(vs_val, str) or not vs_val.strip():
                raise LLMResponseValidationError(
                    f"Required field '{field}' inside video_script is missing or empty."
                )
    else:
        # If no video is present, video_script can be null/None or a dictionary with only empty/null values
        if vs is not None:
            if not isinstance(vs, dict):
                raise LLMResponseValidationError(
                    "Field 'video_script' must be null or a JSON object."
                )
            for field in ["before_video", "after_video", "resume_message"]:
                val = vs.get(field)
                if val is not None and isinstance(val, str) and val.strip():
                    raise LLMResponseValidationError(
                        f"Field 'video_script.{field}' contains non-empty text '{val}' on a slide without videos."
                    )

def validate_faq_response(data: dict):
    """
    Validates global FAQ payload structure.
    """
    faq = data.get("faq")
    if faq is None or not isinstance(faq, list):
        raise LLMResponseValidationError(
            "Required field 'faq' is missing or is not a list in FAQ response."
        )
    for idx, item in enumerate(faq):
        if not isinstance(item, dict):
            raise LLMResponseValidationError(
                f"Element at faq[{idx}] must be a JSON object."
            )
        for field in ["question", "answer"]:
            f_val = item.get(field)
            if not f_val or not isinstance(f_val, str) or not f_val.strip():
                raise LLMResponseValidationError(
                    f"Required field '{field}' inside faq[{idx}] is missing or empty."
                )
        if "confidence" in item and item["confidence"] is not None:
            if not isinstance(item["confidence"], (int, float)):
                raise LLMResponseValidationError(
                    f"Field 'confidence' inside faq[{idx}] must be a float."
                )
        if "references" in item:
            if not isinstance(item["references"], list):
                raise LLMResponseValidationError(
                    f"Field 'references' inside faq[{idx}] must be a list."
                )
            for r_idx, ref in enumerate(item["references"]):
                if not isinstance(ref, int):
                    raise LLMResponseValidationError(
                        f"Element at faq[{idx}].references[{r_idx}] must be an integer."
                    )

def validate_closing_response(data: dict):
    """
    Validates final closing scripts.
    """
    required_strings = ["summary", "congratulations", "next_steps"]
    for key in required_strings:
        val = data.get(key)
        if not val or not isinstance(val, str) or not val.strip():
            raise LLMResponseValidationError(
                f"Required field '{key}' is missing, empty, or not a string in closing response."
            )
