"""add_recipients_to_invitation_draft

Revision ID: 06ce74eada25
Revises: 52d87f218d53
Create Date: 2026-08-10 15:56:06.370477

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ce74eada25'
down_revision: Union[str, None] = '52d87f218d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_drafts', sa.Column('recipients', sa.String(), nullable=True))
    op.alter_column('invitation_drafts', 'recipient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invitation_drafts', 'recipient_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation_drafts', 'recipient_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invitation_drafts', 'recipient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('invitation_drafts', 'recipients')
    # ### end Alembic commands ###
