"""initial_schema

Revision ID: 52d87f218d53
Revises: None
Create Date: 2026-08-07 17:07:25.396617

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d87f218d53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configuration',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('browser_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('edge_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_lists_name'), 'employee_lists', ['name'], unique=False)
    op.create_table('organization_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_domain', sa.String(), nullable=False),
    sa.Column('ai_officer_name', sa.String(), nullable=False),
    sa.Column('ai_trainer_name', sa.String(), nullable=False),
    sa.Column('ai_role_description', sa.String(), nullable=False),
    sa.Column('vocal_tone', sa.String(), nullable=False),
    sa.Column('communication_style', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_name'), 'presentations', ['name'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_voice_id'), 'voice_profiles', ['voice_id'], unique=True)
    op.create_table('presentation_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('presentation_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_assets_presentation_id'), 'presentation_assets', ['presentation_id'], unique=False)
    op.create_table('presentation_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('presentation_id', sa.String(), nullable=False),
    sa.Column('slide_count', sa.Integer(), nullable=False),
    sa.Column('generation_date', sa.DateTime(), nullable=True),
    sa.Column('generation_status', sa.String(), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('last_ai_generation', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_metadata_presentation_id'), 'presentation_metadata', ['presentation_id'], unique=False)
    op.create_table('presentation_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('presentation_id', sa.String(), nullable=False),
    sa.Column('questions_content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_questions_presentation_id'), 'presentation_questions', ['presentation_id'], unique=False)
    op.create_table('presentation_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('presentation_id', sa.String(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_scripts_presentation_id'), 'presentation_scripts', ['presentation_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('creation_mode', sa.String(), nullable=False),
    sa.Column('package_version', sa.String(), nullable=True),
    sa.Column('package_path', sa.String(), nullable=True),
    sa.Column('presentation_id', sa.String(), nullable=True),
    sa.Column('employee_list_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_list_id'], ['employee_lists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_employee_list_id'), 'sessions', ['employee_list_id'], unique=False)
    op.create_index(op.f('ix_sessions_name'), 'sessions', ['name'], unique=False)
    op.create_index(op.f('ix_sessions_presentation_id'), 'sessions', ['presentation_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('attendee_name', sa.String(), nullable=False),
    sa.Column('attendee_email', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_session_id'), 'attendances', ['session_id'], unique=False)
    op.create_table('invitation_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_drafts_session_id'), 'invitation_drafts', ['session_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('teams_meeting_url', sa.String(), nullable=False),
    sa.Column('meeting_passcode', sa.String(), nullable=True),
    sa.Column('organizer_name', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.String(), nullable=False),
    sa.Column('meeting_time', sa.String(), nullable=False),
    sa.Column('meeting_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_session_id'), 'meetings', ['session_id'], unique=False)
    op.create_table('presentation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_jobs_session_id'), 'presentation_jobs', ['session_id'], unique=False)
    op.create_table('runtime_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('speaker_name', sa.String(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_messages_session_id'), 'runtime_messages', ['session_id'], unique=False)
    op.create_table('runtimes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('browser_state', sa.String(), nullable=True),
    sa.Column('induction_state', sa.String(), nullable=True),
    sa.Column('current_slide', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=False),
    sa.Column('meeting_status', sa.String(), nullable=True),
    sa.Column('speech_state', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtimes_session_id'), 'runtimes', ['session_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('upload_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_session_id'), 'uploads', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_session_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_runtimes_session_id'), table_name='runtimes')
    op.drop_table('runtimes')
    op.drop_index(op.f('ix_runtime_messages_session_id'), table_name='runtime_messages')
    op.drop_table('runtime_messages')
    op.drop_index(op.f('ix_presentation_jobs_session_id'), table_name='presentation_jobs')
    op.drop_table('presentation_jobs')
    op.drop_index(op.f('ix_meetings_session_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_invitation_drafts_session_id'), table_name='invitation_drafts')
    op.drop_table('invitation_drafts')
    op.drop_index(op.f('ix_attendances_session_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_sessions_presentation_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_employee_list_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_presentation_scripts_presentation_id'), table_name='presentation_scripts')
    op.drop_table('presentation_scripts')
    op.drop_index(op.f('ix_presentation_questions_presentation_id'), table_name='presentation_questions')
    op.drop_table('presentation_questions')
    op.drop_index(op.f('ix_presentation_metadata_presentation_id'), table_name='presentation_metadata')
    op.drop_table('presentation_metadata')
    op.drop_index(op.f('ix_presentation_assets_presentation_id'), table_name='presentation_assets')
    op.drop_table('presentation_assets')
    op.drop_index(op.f('ix_voice_profiles_voice_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_presentations_name'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_table('organization_config')
    op.drop_index(op.f('ix_employee_lists_name'), table_name='employee_lists')
    op.drop_table('employee_lists')
    op.drop_table('browser_profiles')
    op.drop_table('agent_configuration')
    # ### end Alembic commands ###
