"""add_presentation_slides_table

Revision ID: d658e879739e
Revises: e5f5e3ccfae7
Create Date: 2026-07-30 16:24:48.806783

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd658e879739e'
down_revision: Union[str, None] = 'e5f5e3ccfae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_slides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('visual_hash', sa.String(), nullable=True),
    sa.Column('perceptual_hash', sa.String(), nullable=True),
    sa.Column('audio_file', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_slides_session_id'), 'presentation_slides', ['session_id'], unique=False)
    op.alter_column('runtimes', 'speech_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('runtimes', 'current_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('current_step', sa.VARCHAR(), nullable=True))
    op.alter_column('runtimes', 'speech_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_presentation_slides_session_id'), table_name='presentation_slides')
    op.drop_table('presentation_slides')
    # ### end Alembic commands ###
