"""add_runtime_lifecycle_columns

Revision ID: e5f5e3ccfae7
Revises: 001_add_job_type
Create Date: 2026-07-25 20:31:05.709590

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f5e3ccfae7'
down_revision: Union[str, None] = '001_add_job_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('presentation_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_assets_presentation_id'), 'presentation_assets', ['presentation_id'], unique=False)
    op.add_column('runtimes', sa.Column('browser_state', sa.String(), nullable=True, server_default="NOT_CREATED"))
    op.add_column('runtimes', sa.Column('induction_state', sa.String(), nullable=True, server_default="NOT_CREATED"))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('current_step', sa.VARCHAR(), nullable=True))
    op.alter_column('runtimes', 'speech_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('runtimes', 'induction_state')
    op.drop_column('runtimes', 'browser_state')
    op.drop_index(op.f('ix_presentation_assets_presentation_id'), table_name='presentation_assets')
    op.drop_table('presentation_assets')
    # ### end Alembic commands ###
