from enum import Enum

class ObservationEvent(str, Enum):
    NONE = "NONE"
    PRESENTATION_STARTED = "PRESENTATION_STARTED"
    PRESENTATION_ENDED = "PRESENTATION_ENDED"
    SLIDE_CHANGED = "SLIDE_CHANGED"
    SCREEN_SHARE_STARTED = "SCREEN_SHARE_STARTED"
    SCREEN_SHARE_STOPPED = "SCREEN_SHARE_STOPPED"
    CHAT_OPENED = "CHAT_OPENED"
    CHAT_CLOSED = "CHAT_CLOSED"
    PARTICIPANTS_OPENED = "PARTICIPANTS_OPENED"
    PARTICIPANTS_CLOSED = "PARTICIPANTS_CLOSED"
    RECORDING_STARTED = "RECORDING_STARTED"
    RECORDING_STOPPED = "RECORDING_STOPPED"
    WAITING = "WAITING"
    LOADING = "LOADING"
