from enum import Enum

class SessionStatus(str, Enum):
    PENDING = "PENDING"
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    PARSING = "PARSING"
    GENERATING_SCRIPT = "GENERATING_SCRIPT"
    GENERATING_AUDIO = "GENERATING_AUDIO"
    REGISTERING_ASSETS = "REGISTERING_ASSETS"
    VERIFYING = "VERIFYING"
    READY = "READY"
    FAILED = "FAILED"

class UploadType(str, Enum):
    PRESENTATION = "PRESENTATION"
    EMPLOYEE_LIST = "EMPLOYEE_LIST"
    REPORT = "REPORT"
    AUDIO = "AUDIO"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"

class JobStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class TaskStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
